apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alerts.heimdall.uswitch.com
spec:
  group: heimdall.uswitch.com
  version: v1alpha1
  names:
    kind: Alert
    plural: alerts
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            expr:
              type: string
            for:
              type: string
