---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: heimdall
  name: heimdall
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
        - name: templates
          configMap:
            name: heimdall-templates
      containers:
      - name: heimdall
        image: quay.io/uswitch/heimdall:v0.2
        args:
        - --json
        - --configmap-name=heimdall-config
        - --configmap-namespace=kube-system
        - --templates=/etc/templates
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 512m
            memory: 100Mi
        volumeMounts:
          - name: templates
            mountPath: /etc/templates
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-templates
  namespace: kube-system
data:
  5xx-rate.tmpl: |
    groups:
    - name: 5xx-rate-{{.Identifier}}.rules
      rules:
      - alert: ServerErrorAlert
        expr: (sum(rate(nginx_filterzone_responses_total{key="{{.Identifier}}",server_zone="kubernetes::ingress",status_code="5xx"}[10s]))/ sum(rate(nginx_filterzone_responses_total{key="{{.Identifier}}",server_zone="kubernetes::ingress"}[10s]))) > {{.Threshold}}
        for: 1m
        labels:
          identifier: {{.Identifier}}
          name: {{.Name}}
          namespace: {{.Namespace}}
        annotations:
          summary: '{{.Identifier}}: 5xx proportion above {{.Threshold}} for 1m'
  response-msec-threshold.tmpl: |
    groups:
    - name: response-msec-threshold-{{.Identifier}}.rules
      rules:
      - alert: ResponseMsecAlert
        expr: avg(nginx_filterzone_request_msecs_avg{key="{{.Identifier}}",server_zone="kubernetes::ingress"}) > {{.Threshold}}
        for: 5m
        labels:
          identifier: {{.Identifier}}
          name: {{.Name}}
          namespace: {{.Namespace}}
        annotations:
          summary: '{{.Identifier}}: Response time has been above {{.Threshold}}ms for 5m'
